import fs from 'fs';
import path from 'path';

// Crear una imagen PNG válida (100x100 píxeles) para subir en Bing Visual Search
const assetsDir = path.join(process.cwd(), 'assets');
if (!fs.existsSync(assetsDir)) {
  fs.mkdirSync(assetsDir, { recursive: true });
}

const samplePngBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QgXDRw5yR5mJAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAABhElEQVR42u3SMQEAAAjAMMC/521hBw9IQLbO3g5EAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEiAARIkCECBChgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIUJEiAARIkCECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEiAARIECECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEiAARIECECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEgAARIkCECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEiAARIECECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEgAARIkCECBABAiJEgAgRIEIEiBABIkSACBEgQgSIEAECRIgAESJAhAgQIQJEgAARIkCECBABAiJEgAgRIEIEiAAR+wF5lQAB24W1gAAAAABJRU5ErkJggg==';

const imagePath = path.join(assetsDir, 'sample_search.png');
fs.writeFileSync(imagePath, Buffer.from(samplePngBase64, 'base64'));

export const searchImagePath = imagePath;
